#!/usr/bin/csh -f


sudo /home/admin/mrtrix3/release/bin/tckgen -algorithm Tensor_Prob -seed_image 7.FLIRT/cluster-573-complete.nii.gz -include 7.FLIRT/cluster-573.nii.gz -number 0 -fslgrad 6.forbedpost/bvecs 6.forbedpost/bvals -nthreads 4 -info -maxnum 100000 6.forbedpost/data.nii.gz mrtrix/tck/cluster-5573-TP-0-100000.tck
