#!/usr/bin/csh -f

# subject list
set subject_list = "ab99_7777 xy77_9999"               

foreach SID ($subject_list)                      #if you have a subject list
  echo $SID
  echo
  set fileroot = /data/study/Fibertracking/$SID  #an example folder
  set MPRAGEDIR = $fileroot/MPRAGE_Template_08   # an subfolder with MPRAGE data
  # find MPRAGE file
  set MPRAGEFILE = `echo {$MPRAGEDIR}/o*MPRAGE*001.nii | awk '{print(substr($1,1, length($1)-4))}'`  # MPRAGE file is converted with dcm2niigui (mricron) from DICOM
  echo "MPRAGE:"
  echo $MPRAGEFILE
  echo " "
  # perform ACT
  /home/jkauf/mrtrix3/scripts/act_anat_prepare_fsl {$MPRAGEFILE}.nii {$MPRAGEFILE}_ACT.nii -nthreads 4
  set ACT_FILE = {$MPRAGEFILE}_ACT.nii
  set DATADIR = /data_2851/thilorusche/Fibertracking/{$SID}/average_inv_undist
  set T1ROIDIR = $fileroot/ROI_T1/ROIs_2_average_inv_undist
    
  set MPRAGE_2_Diff = `echo $DATADIR/o*MPRAGE*_coreg2nodif*`
  echo $MPRAGE_2_Diff
  echo
  
  cd $DATADIR
  echo $DATADIR
  echo
  #create mask.nii
  dwi2mask -info -fslgrad bvecs bvals data.nii -force mrtrix_mask.nii
  echo
  #compute response funktion
  dwi2response -fslgrad bvecs bvals -shell 1000 -mask mrtrix_mask.nii -lmax 10 -sf single-fibre-voxels.nii -test_all -nthreads 4 -force -info data.nii response_out
  echo
  #fit the SH-FOD-file (contrained spherical harmonics)
  dwi2fod -fslgrad bvecs bvals -shell 1000 -mask mrtrix_mask.nii -lmax 10 -nthreads 4 -force -info data.nii response_out SH_FOD_file.nii

  mkdir $DATADIR/Fibres
  mkdir $DATADIR/Fibres/VP
  mkdir $DATADIR/Fibres/VP/NAc_2_Target_ACT
  mkdir $DATADIR/Fibres/VP/Target_2_NAc_ACT
  
  mkdir $DATADIR/Fibres/VP/NAc_2_Target_ACT/NAc_Re_Target_Re_ACT
  mkdir $DATADIR/Fibres/VP/Target_2_NAc_ACT/Target_Re_NAc_Re_ACT
  
  set NUMBER = 100000
  echo $DATADIR
  echo number: $NUMBER

  # forward direction
  
  # NAc_2_Target_ACT/NAc_Re_Target_Re_ACT
  echo
  echo "NAc_2_Target_ACT/NAc_Re_Target_Re_ACT"
  echo
  set OUTPUTDIR = $DATADIR/Fibres/VP/NAc_2_Target_ACT/NAc_Re_Target_Re_ACT
  # input ROI finden
  set INPUT_ROI = `echo $T1ROIDIR/bin_0.5_coreg2diff_*_T1_Template_08-mask_NAc_Re.nii`
  echo $INPUT_ROI
  set len_NAc_2_VP = 10
  set EXCLUDE_ROI1 = $T1ROIDIR/Excl_ROI_N_opticus_distal.mif
  set EXCLUDE_ROI2 = $T1ROIDIR/Excl_ROI_N_opticus_proximal.mif
  set INCLUDE_ROI  = `echo $T1ROIDIR/bin_0.5_coreg2diff_*_T1_Template_08-mask_VP_Re.nii`
  tckgen $DATADIR/SH_FOD_file.nii $OUTPUTDIR/NAc_Re_to_VP_Re_b1000_"$len_NAc_2_VP"_mm_"$SID"_ACT.tck -seed_image $INPUT_ROI -include $INCLUDE_ROI -act $ACT_FILE -exclude $EXCLUDE_ROI1 -exclude $EXCLUDE_ROI2 -force -number $NUMBER -fslgrad $DATADIR/bvecs $DATADIR/bvals -nthreads 4 -info -unidirectional -maxlength $len_NAc_2_VP

  #creation of density maps (the same as fdt_path in fsl)
  cd $OUTPUTDIR
  foreach map_tck (*ACT.tck)
    echo $map_tck
    tckmap $OUTPUTDIR/$map_tck -template $MPRAGE_2_Diff $OUTPUTDIR/"map_16_ACT_"$map_tck.nii -force
    tckmap $OUTPUTDIR/$map_tck -template {$MPRAGEFILE}.nii $OUTPUTDIR/"map_08_ACT_"$map_tck.nii -force
  end
  
    
  # backward
  
  # Target_2_NAc_ACT/Target_Re_NAc_Re_ACT
  echo
  echo "Target_2_NAc_ACT/Target_Re_NAc_Re_ACT"
  echo
  set OUTPUTDIR = $DATADIR/Fibres/VP/Target_2_NAc_ACT/Target_Re_NAc_Re_ACT
  # input ROI finden
  set INPUT_ROI = `echo $T1ROIDIR/bin_0.5_coreg2diff_*_T1_Template_08-mask_VP_Re.nii`
  echo $INPUT_ROI
  set len_NAc_2_VP = 10
  set EXCLUDE_ROI1 = $T1ROIDIR/Excl_ROI_N_opticus_distal.mif
  set EXCLUDE_ROI2 = $T1ROIDIR/Excl_ROI_N_opticus_proximal.mif
  set INCLUDE_ROI  = `echo $T1ROIDIR/bin_0.5_coreg2diff_*_T1_Template_08-mask_NAc_Re.nii`
  tckgen $DATADIR/SH_FOD_file.nii $OUTPUTDIR/VP_Re_to_NAc_Re_b1000_"$len_NAc_2_VP"_mm_"$SID"_ACT.tck -seed_image $INPUT_ROI -include $INCLUDE_ROI -act $ACT_FILE -exclude $EXCLUDE_ROI1 -exclude $EXCLUDE_ROI2 -force -number $NUMBER -fslgrad $DATADIR/bvecs $DATADIR/bvals -nthreads 24 -info -unidirectional -maxlength $len_NAc_2_VP

  cd $OUTPUTDIR
  foreach map_tck (*ACT.tck)
    echo $map_tck
    tckmap $OUTPUTDIR/$map_tck -template $MPRAGE_2_Diff $OUTPUTDIR/"map_16_ACT_"$map_tck.nii -force
    tckmap $OUTPUTDIR/$map_tck -template {$MPRAGEFILE}.nii $OUTPUTDIR/"map_08_ACT_"$map_tck.nii -force
  end
  
    
end #over subject list
