function rendfile = getRenderFile(settings)
        
rendfile = strcat(settings.folders.main,'\',...
    settings.folders.experiment,'\',...
    settings.folders.subject,'\',...
    settings.folders.preprocessed,'\',...
    settings.anatomical.folder.main,'\',...
    settings.anatomical.run(1).folder,'\',...
    settings.anatomical.run(1).render.folder,'\',...
    settings.anatomical.run(1).render.file);
        
end
